version: "3.4"
# I wrote this file initally to work with postgress but due to
# node module and time I choosed mysql as an Alternative.
# Just to show the effort.
services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=socketdb
    ports:
      - "5432:80"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
